### ISSUE TITLE
Does not support Unicode characters

### ISSUE THREAD

**Issue by alekdavis** [szafranek/delicious-exporter#3] opened 2017-02-15 06:14 UTC
The tools seems to work with English characters set only, so if there are page titles, descriptions or tags in other character sets, they seem to be corrupted.

**Comment by szafranek** [comment] 2017-03-24 07:40
I tested it with a page with Unicode characters and all was saved just fine. Could you please provide more details, e.g. what was the page and on which platform were you running the script (mac/win)?

**Comment by alekdavis** [comment] 2017-03-26 06:37
I must have done something to the generated file, so can't share the results at the moment, but, try these URLs:

http://www.chaskor.ru/article/umberto_eko_14_priznakov_fashizma_35975 (Умберто Эко: 14 признаков фашизма :: Частный Корреспондент)
http://www.colta.ru/articles/society/5977 (Леонид Смирнягин: «Америка? Важно, что мы ее ненавидим, и всё» | Colta.ru)
http://www.sergeydovlatov.ru/ (Биография, афоризмы, статьи, романы, рассказы, повести, интервью, рисунки - Довл...)

I'm using Windows 10.

**Comment by szafranek** [comment] 2017-03-26 19:03
I bookmarked one of these sites, added title and description in Cyrillic, and all was exported correctly. Are you using a recent version of Ruby? I tested it on 2.3.0. I know that Ruby 1.x had problems with Unicode.

I'm testing on a mac, though. Perhaps it's an issue with Windows. Pull requests are welcome :).

**Comment by alekdavis** [comment] 2017-03-27 20:32
I used the latest version of Ruby, so it's probably a Windows issue then. I'll give it another try, when I get a chance.

**Comment by szafranek** [comment] 2017-08-27 13:07
There wasn't any followup and I couldn't reproduce it, so I'm closing it.

**Closed as completed by szafranek** 2017-08-27 13:07 UTC
Labels: invalid
